### ISSUE TITLE
Driver sends an empty query

### ISSUE THREAD

**Issue by alexesDev** [pyrooka/metabase-cubejs-driver#37]
Hi. I installed the plugin and nothing works...
After after adding the database, cubejs got two requests with empty query:
```
/cubejs-api/v1/meta?query= HTTP/1.1
authorization: xxx
accept: application/json
accept-encoding: gzip, deflate
host: analytics-xxx.local
user-agent: Apache-HttpClient/4.5.5 (Java/11.0.3)

GET /cubejs-api/v1/meta?query= HTTP/1.1
authorization: xxx
accept: application/json
accept-encoding: gzip, deflate
host: analytics-xxx.local
user-agent: Apache-HttpClient/4.5.5 (Java/11.0.3)
```

Metabase: v0.33.6
@cubejs-backend/server@0.13.5

What am I doing wrong?

**Comment by pyrooka** [comment]
Hi,
Sorry for the late reply, but the holidays. Your problem is strange. I will publish a new release in a few days, so you can give it a try. If the problem still exists I investigate it.

**Comment by pyrooka** [comment]
I've just dropped a new release. You can get it from [HERE](https://github.com/lili-data/metabase-cubejs-driver/releases/tag/v0.5.0), but note that it only works with Metabase v0.34.0 or newer from now. Please close the issue if it is working or provide some more details if not.

**Comment by alexesDev** [comment]
Hi,
I upgrade Metabase and the plugin, but I have same results. What details can I provide?

**Comment by pyrooka** [comment]
Okay, I've noticed that the endpoint in your requests is the [cube.js meta](https://cube.dev/docs/rest-api#api-reference-v-1-meta), which responses with the metadata about your data.

What are you doing when you get this? Just because this endpoint only used when the driver fetching the schema from the Cube.js REST API.
Can you try to re-add the DB to Metabase if you haven't done it yet?

If the above solution doesn't work:
1. If you select the whole table do you get any result?
2. Is the native query working?
3. Do you see any error in the Metabase log?

Sorry if this comment a little bit messy, but I haven't faced any issues like this.

**Comment by alexesDev** [comment]
Sorry, my bad. I found in the logs
```
ERROR: insert or update on table "metric"
violates foreign key constraint "fk_metric_ref_creator_id"
Key (creator_id)=(1) is not present in table "core_user".
```
Then I found
https://github.com/lili-data/metabase-cubejs-driver/blob/master/src/metabase/driver/cubejs.clj#L267
Then I rebuild plugin with valid creater_id and now it works.

Thanks for the plugin :+1:

**Comment by pyrooka** [comment]
Glad you found the problem! I am continuously trying to improve the code, but expect some bugs.
And thanks for using the driver!
