### ISSUE TITLE
Store field information in the description as a JSON

### ISSUE THREAD

**Issue by pyrooka** [pyrooka/metabase-cubejs-driver#49]
At the moment all the field information stored as a simple text in the description fields. Also, we use the field and metric names for the Cube.js query, hence they are sensitive to renaming.

Proposal:
Save every piece of information into a JSON. This is more futureproof and easier to extend.

**Comment by norbertbede** [comment]
> Norbert Bede Today at 10:25 AM
issue> Store field information in the description as a JSON

Norbert Bede  5 hours ago
the question here is why we are not able to store data into metric table definition field

Norbert Bede  5 hours ago
the reason is ATM if metabase user will check help then json will be visible

Norbert Bede  5 hours ago
@Igor Pojzl please take a look is it an option or driver API has access to this field.

Norbert Bede  5 hours ago
in my opinion json is generic format, and doesn't sensitive to new key/value improvment

Norbert Bede  5 hours ago
sure depends on MB api

Norbert Bede  5 hours ago
@bn we are let you our review of api

Igor Pojzl  5 hours ago
In Metabase we have TableMetadataField interface:
(def TableMetadataField
  "Schema for a given Field as provided in `describe-table`."
  {:name                           su/NonBlankString
   :database-type                  (s/maybe su/NonBlankString) ; blank if the Field is all NULL & untyped, i.e. in Mongo
   :base-type                      su/FieldType
   (s/optional-key :special-type)  (s/maybe su/FieldType)
   (s/optional-key :field-comment) (s/maybe su/NonBlankString)
   (s/optional-key :pk?)           s/Bool
   (s/optional-key :nested-fields) #{(s/recursive #'TableMetadataField)}
   (s/optional-key :custom)        {s/Any s/Any}})
Can we use optional key custom to store JSON?
https://github.com/metabase/metabase/blob/master/src/metabase/sync/interface.clj (edited) 

bn  5 hours ago
To store the original metric (measure) name the definiton column would be good imo, so I go with this.

bn  5 hours ago
About the field meta data: I give it a try to store the data in the custom field but I cannot predict the result because I don’t find this column in my metabase DB. (edited) 

Norbert Bede  3 hours ago
FYI: we are tested metric - we have added a new json key-pair - as we plan - and gui survive, app looks ok.

Norbert Bede  2 hours ago
I have created on H2 db demo an example metric: the contentis follow
{
   "source-table":2,
   "aggregation":[
      [
         "cum-sum",
         [
            "field-id",
            6
         ]
      ]
   ],
   "filter":[
      "=",
      [
         "field-id",
         2
      ],
      10
   ]
}
(edited)

Norbert Bede  1 hour ago
@bn @Igor Pojzl i summarise my perspective to this metric/dimension imrovment
change candidates are: (manager overview)
improvement - put/get metric cubejs fieldname into the metric.definition field json structure (this allow rename metric as we want) - this broke fully existing metrics and queries.
connect metric and dimension - this can be complicated  - this means fill out a specific json in metric.definition
improvement - metabase columns - put/get cubejs meta data (measure/dimension) into custom column
 (edited) 

bn  1 hour ago
I have done the 1. already, just review my changes, update the readme maybe then commit.
:definition  {:source-table (:id table)
              :cube-name  (:name measure)
              :aggregation ...}

Norbert Bede  1 hour ago
i see

Norbert Bede  1 hour ago
ok we are waiting to commit then we start test immediately

bn  1 hour ago
no need for the 2, because fields have a name  and a separate display_name. In MBQL the name is used.

bn  1 hour ago
If I understand correctly

Norbert Bede  1 hour ago
it is related soon to model - later -  cubejs measure to - meta base metric - let say som of column qty => then metabase should correctly describe to user what is calculated (long term prio :slightly_smiling_face:)

Norbert Bede  15 minutes ago
@bn any instruction how to reload existing metrics ? (edited) 

bn  14 minutes ago
if you can readd the db that would be the best

Norbert Bede  13 minutes ago
uf. we rename mostly fields yesterday :slightly_smiling_face:

Norbert Bede  13 minutes ago
ok

Norbert Bede  13 minutes ago
then test it firs locally with clean one

bn  13 minutes ago
if you cannont, you have to delete the metrics then hit the sync db schema or something like this button on the db page

bn  12 minutes ago
yeah, that’s a good idea, also you can try the second solution. i think that sould be work well too

Norbert Bede  11 minutes ago
new fields were added, old are not deleted well (edited) 

Norbert Bede  9 minutes ago
resolved. i have deleted old metrics in db :slightly_smiling_face: (edited) 

Norbert Bede  4 minutes ago
just confirming: field saved properly when db synced. Then i rename field, still works - so we can link cubejs meta fields and allowed rename to local language :+1:
